import { Navbar } from "@/components/Navbar";
import AuthProvider from "@/context/AuthProvider";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SpotifyDash",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className="relative flex flex-col">
            <header className="sticky z-40 top-0 left-0 p-0">
              <Navbar />
            </header>
            <div className="pb-10 px-10">{children}</div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
