import { Navbar } from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SpotifyDash",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative flex flex-col">
          <header className="sticky z-40 top-0 left-0 p-0">
            <Navbar />
          </header>
          <div className="pb-10 px-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
